### ISSUE TITLE
IP blocked from recognize service

### ISSUE THREAD

**Issue by jeremy-bepoix** [duggytuxy/Data-Shield_IPv4_Blocklist#11]
Hi,

These ip are blocked from VPS that can change in 2-3 days and end up with legit blocked services...

This first one is a collaborative HR solution
https://my.silae.fr/sign-in > https://www.nslookup.io/domains/my.silae.fr/webservers/

The second one is a cartoon studio
https://www.supamonks.com/ > https://www.nslookup.io/domains/www.supamonks.com/webservers/

best, 
regards

**Comment by duggytuxy** [comment]
Hi Jeremy,

I just removed these IPv4 from my BL.

Thanks a lot for your contribution.

I'm going to close this ticket.

Sincerely,
Duggy
